version: "3.8"

networks:
  fistin:
    driver: overlay

services:
  redis:
    image: redis:6.2.6-alpine
    networks:
      - fistin
    command: redis-server --requirepass p@ssw0rd

  hydra:
    image: hydra:dev
    networks:
      - fistin
    environment:
      STACK_NAME: hydra
      NETWORK_NAME: fistin
      REDIS_HOST: redis
      REDIS_PASS: p@ssw0rd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock