name: Gradle Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build with Gradle
        run: ./gradlew build
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.TOKEN }}

      - name: Build shaded Jar
        run: ./gradlew shadowJar
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Hydra
          path: build/libs